name: netease_music_api
description: Netease cloud music api for flutter ,reference https://github.com/Binaryify/NeteaseCloudMusicApi.
version: 0.0.3
author: hcanyz
homepage: https://github.com/hcanyz/flutter-netease-music-api

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ext
  collection: ^1.15.0

  # app path
  path_provider: ^2.0.2

  # http
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  dio_cookie_manager: ^2.0.0

  # encrypt
  encrypt: ^5.0.0
  pointycastle: ^3.1.2

  # x json
  json_annotation: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # x json
  build_runner: ^2.0.4
  json_serializable: ^4.1.3

  # mock
  mockito: ^5.0.10